# The path to the local model directory or Hugging Face repo.
model: mlx_model
# Whether or not to train (boolean)
train: true

# Directory with {train, valid, test}.jsonl files
data: "data"

# The PRNG seed
seed: 3407

# Number of layers to fine-tune
lora_layers: 16

# Minibatch size.
batch_size: 2

# Iterations to train for.
iters: 60

# Number of validation batches, -1 uses the entire validation set.
val_batches: -1

# Adam learning rate.
learning_rate: 2e-4

# Number of training steps between loss reporting.
steps_per_report: 5

# Number of training steps between validations.
steps_per_eval: 12

# Load path to resume training with the given adapter weights.
resume_adapter_file: null

# Save/load path for the trained adapter weights.
adapter_path: "adapters"

# Save the model every N iterations.
save_every: 12

# Evaluate on the test set after training
test: true

# Number of test set batches, -1 uses the entire test set.
test_batches: -1

# Maximum sequence length.
max_seq_length: 2048

# Use gradient checkpoint to reduce memory use.
grad_checkpoint: true

# LoRA parameters can only be specified in a config file
lora_parameters:
  # The layer keys to apply LoRA to.
  # These will be applied for the last lora_layers
  keys: ['mlp.gate_proj', 'mlp.down_proj', 'self_attn.q_proj', 'mlp.up_proj', 'self_attn.o_proj','self_attn.v_proj', 'self_attn.k_proj']
  rank: 16
  alpha: 16
  scale: 10.0
  dropout: 0.0

# Schedule can only be specified in a config file, uncomment to use.
lr_schedule:
  name: linear_schedule
  warmup: 5 # 0 for no warmup
  warmup_init: 1e-7 # 0 if not specified
  arguments: [0, 1e-4, 100] # passed to scheduler